### ISSUE TITLE
licence key is appearing as 'expired' on edd

### ISSUE THREAD

**Issue by owaincuvelier** [humanmade/backupwordpress-pro-rackspace#7]
![screen shot 2014-12-12 at 11 34 58](https://cloud.githubusercontent.com/assets/1263370/5410960/fdce26bc-81f2-11e4-8485-b4c9e64097dd.png)

**Comment by pdewouters** [comment]
@owain looks like we lost track of this one. Is it still happening?

**Comment by owaincuvelier** [comment]
Nah this is sorted.
